import sys, re

def format_arbitrationID(arbitrationID:str, outputType:str):
    """Converts an arbitration id in provided int form to hex

    Args:
        arbitrationID (int): arbitration id directly from the unedited .dbc file (not generated by this code)

    Returns:
        int: arbitration id in hex form, which in Python, is an int under the hood
    """
    # Convert to hex
    hexID = hex(int(arbitrationID))
    
    # hexID string starts with '0x', first hex digit is at index 3
    # The leftmost three bits of the hex should be '100', but the 
    # rightmost bit belongs to priority. To preserve it, we will check
    # if it is 1 by seeing if it is an odd number
    hexID =  "0x9" + hexID[3:] if (int(hexID[2], 16) % 2) else "0x8" + hexID[3:]
    
    if outputType == "byte": hexID = bytes.fromhex(hexID)
    elif outputType == "int": hexID = int(hexID, 16)
    
    # print(hexID)  # Debug
    return hexID

def scrape_dbc_for_gateways(filePath:str):
    """This function will scrape a provided `.dbc` file for all gateways, and put them in a new `.dbc` file named `scrapedGateways.dbc`.
    If the `scrapedGateways.dbc` already exists, user will be prompted before running the program to avoid overwriting existing content.
    
    Note that arbitration IDs will be displayed as integers, but hex numbers are ultimately int types under the hood in Python.

    Args:
        filePath (str): The filepath (absolute or local) of the `.dbc` file to be scraped
        
    Returns:
        scrapedName (str): The filepath of the results of the scraped `.dbc`
    """    
    try:
        dbcFile = open(filePath, 'r')
        # If we could not open the file
    except OSError:
        print("Error: could not open/read file ", filePath)
        sys.exit()

    
    with dbcFile:
        # A map of unaltered arbitration IDs to a list of all specified gateways
        toReturn_dict:dict[str, list[str]] = {}
        
        # Get the first line (fencepost problem)
        curLineUnparsed = dbcFile.readline()
        while curLineUnparsed: # While there's still a line in the file
            # Splitting by double quotes, rather than spaces, makes things slightly easier
            curLineParsed = curLineUnparsed.split('"')
            # All gateways necessarily start with 'BA_ "Network"'
            # Note that not every line with 'BA_ "Network"' is a gateway
            if len(curLineParsed) > 2 and curLineParsed[0].strip() == "BA_" and curLineParsed[1].strip() == "Network":
                # Because we parsed by double quotes, the very last element in the array of
                # tokens will be a semicolon, and the second to last element will be the
                # specified CAN channel (port?)
                
                # It is a gateway if and only if a colon is present
                if re.match(r".+:", curLineParsed[3]):
                    # Get arbitration ID of this gateway
                    arbitrationID = re.search(r"\d+", curLineParsed[2])
                    # re.search() returns an object, we just want the string
                    if arbitrationID: arbitrationID = arbitrationID.string
                    # We just want the number
                    arbitrationID = arbitrationID.split(" ")[2].strip()
                    # print(arbitrationID)  # Debug
                    # Note that in python, hex numbers are ints under the hood
                    # arbitrationID = arbitrationID_toHex(arbitrationID)
                    
                    # In case there are multiple gateways
                    allGateways = curLineParsed[3].split(",")
                    allGateways = [g.strip() for g in allGateways]
                    # print(allGateways)  # Debug
                    
                    toReturn_dict[arbitrationID] = allGateways
                
                '''
                    All gateway specifications start with 'BA_', followed by
                    ' "Network" ', 
                    matches this regex { \d ".*:.*"; }
                    
                '''
                # match = re.search(r'\d ".*:.*";', curLineUnparsed)
                
            curLineUnparsed = dbcFile.readline()
    
    return toReturn_dict
                        
if __name__ == "__main__":
    if len(sys.argv) > 1:
        if (sys.argv[1] == "gateway.dbc"):
            scrape_dbc_for_gateways(sys.argv[2])
        elif (sys.argv[1] == "hex"):
           format_arbitrationID(sys.argv[2], sys.argv[3])
    else:
        print("Utils: Pass an argument bro")