import sys, re

def loadFilePath(fileToLoad:str):
    """Loads the file path specified in `filepath.txt`

    Args:
        fileToLoad (str): Args are either `primaryDBC`, `secondaryDBC`, or `cfg`

    Returns:
        str|None: Returns the filepath based on the spec. If none of the three specific args are entered, returns None
    """
    try:
        dbcFile = open("filepath.txt", 'r')
        dbcFile.readable()
        # If we could not open the file
    except OSError:
        print("Error: could not open/read file ", "filepath.txt")
        sys.exit()
        
    with dbcFile:
        dbcFile.readline()
        primaryDBC = dbcFile.readline().strip().strip("\"")
        dbcFile.readline()
        secondaryDBC = dbcFile.readline().strip().strip("\"")
        dbcFile.readline()
        cfg = dbcFile.readline().strip().strip("\"")
        
        if fileToLoad == "primaryDBC": return primaryDBC
        if fileToLoad == "secondaryDBC": return secondaryDBC
        if fileToLoad == "config": return cfg
        
        return None

def format_arbitrationID(arbitrationID:str, outputType:str):
    
    # Let's think about converting this function into one using bit masking
    """Converts an arbitration id in provided int form to hex

    Args:
        arbitrationID (str): arbitration id directly from the unedited .dbc file (not generated by this code)
        outputType (str): Specifying whether the output should be `int` or `byte`

    Returns:
        int: arbitration id in hex form, which in Python, is an int under the hood
    """
    # Convert to hex
    hexID = hex(int(arbitrationID))
    
    # hexID string starts with '0x', first hex digit is at index 3
    # The leftmost three bits of the hex should be '100', but the 
    # rightmost bit belongs to priority. To preserve it, we will check
    # if it is 1 by seeing if it is an odd number
    hexID =  "0x1" + hexID[3:]
    
    if outputType == "byte": hexID = bytes.fromhex(hexID)
    elif outputType == "int": hexID = int(hexID, 16)
    
    # print(hexID)  # Debug
    return hexID

def scrape_dbc_for_gateways(filePath:str):
    """This function will scrape a provided `.dbc` file for all gateways, and put them in a new `.dbc` file named `scrapedGateways.dbc`.
    If the `scrapedGateways.dbc` already exists, user will be prompted before running the program to avoid overwriting existing content.
    
    Note that arbitration IDs will be displayed as integers, but hex numbers are ultimately int types under the hood in Python.

    Args:
        filePath (str): The filepath (absolute or local) of the `.dbc` file to be scraped
        
    Returns:
        scrapedName (str): The filepath of the results of the scraped `.dbc`
    """    
    try:
        dbcFile = open(filePath, 'r')
        # If we could not open the file
    except OSError:
        print("Error: could not open/read file ", filePath)
        sys.exit()

    
    with dbcFile:
        # A map of unaltered arbitration IDs to a list of all specified gateways
        toReturn_dict:dict[str, list[str]] = {}
        
        # Get the first line (fencepost problem)
        curLineUnparsed = dbcFile.readline()
        while curLineUnparsed: # While there's still a line in the file
            # Splitting by double quotes, rather than spaces, makes things slightly easier
            curLineParsed = curLineUnparsed.split('"')
            # All gateways necessarily start with 'BA_ "Network"'
            # Note that not every line with 'BA_ "Network"' is a gateway
            if len(curLineParsed) > 2 and curLineParsed[0].strip() == "BA_" and curLineParsed[1].strip() == "Network":
                # Because we parsed by double quotes, the very last element in the array of
                # tokens will be a semicolon, and the second to last element will be the
                # specified CAN channel (port?)
                
                # It is a gateway if and only if a colon is present
                if re.match(r".+:", curLineParsed[3]):
                    # Get arbitration ID of this gateway
                    arbitrationID = re.search(r"\d+", curLineParsed[2])
                    # re.search() returns an object, we just want the string
                    if arbitrationID: arbitrationID = arbitrationID.string
                    # We just want the number
                    arbitrationID = arbitrationID.split(" ")[2].strip()
                    # print(arbitrationID)  # Debug
                    # Note that in python, hex numbers are ints under the hood
                    # arbitrationID = arbitrationID_toHex(arbitrationID)
                    
                    # In case there are multiple gateways
                    allGateways = curLineParsed[3].split(",")
                    allGateways = [g.strip() for g in allGateways]
                    # print(allGateways)  # Debug
                    
                    toReturn_dict[arbitrationID] = allGateways
                
                '''
                    All gateway specifications start with 'BA_', followed by
                    ' "Network" ', 
                    matches this regex { \d ".*:.*"; }
                    
                '''
                # match = re.search(r'\d ".*:.*";', curLineUnparsed)
                
            curLineUnparsed = dbcFile.readline()
    
    return toReturn_dict

def generate_j1939_22_envelope(int_arbitrationID:int, dummy_data:list):
    """Dynamically packs an 8-byte J1939 payload into a 12-byte J1939-22 CAN-FD envelope (PGN 9472 / 0x25000).
    Uses bitwise operations for high-performance execution.

    Args:
        int_arbitrationID (int): The original Standard CAN arbitration ID
        dummy_data (list): The 8-byte payload data array

    Returns:
        tuple: (envelope_id as int, envelope_payload as list)
    """
    pdu_format = (int_arbitrationID >> 16) & 0xFF
    pdu_specific = (int_arbitrationID >> 8) & 0xFF

    if pdu_format < 240:
        byte_2 = 0x00
        container_ps = pdu_specific
    else:
        byte_2 = pdu_specific
        container_ps = 0xFF
    
    header = [0x40, pdu_format, byte_2, 0x08]
    priority_edp_dp_sa = int_arbitrationID & 0x1F0000FF
    
    envelope_id = priority_edp_dp_sa | (0x25 << 16) | (container_ps << 8)
    envelope_payload = header + dummy_data
    
    return envelope_id, envelope_payload


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if (sys.argv[1] == "gateway.dbc"):
            scrape_dbc_for_gateways(sys.argv[2])
        elif (sys.argv[1] == "hex"):
           format_arbitrationID(sys.argv[2], sys.argv[3])
        elif (sys.argv[1] == "loadFilePath"):
            print(loadFilePath(sys.argv[2]))
    else:
        print("Utils: Pass an argument bro")